/** All copy for the sheet lives here so the generators stay layout-only. */

export const USER = 'btfcookies';

export const HEADER = {
  eyebrow: 'HEAD DEVELOPER — EIGHTBIT LABS',
  name: ['LAWRENCE', 'TONG'],
  handle: '@btfcookies · cookiemonster',
  prose:
    'Developer tools and Discord bots by day. Also a PDF rendering API, a quiz bowl practice site, and a cryptocurrency named after Terry A. Davis.',
  caption: '1-BIT RASTER · 128×128 · ATKINSON',
};

export const RASTER_SETTINGS = { size: 128, gamma: 2.5, gain: 1.0 };

export const PROJECTS = {
  eyebrow: 'SELECTED WORK',
  rows: [
    {
      name: 'REAMUS',
      blurb: 'An API that turns HTML into PDFs. No browser for you to run.',
      url: 'reamus.app',
    },
    {
      name: 'ORBIS',
      blurb: 'Discord bots for the parts of a developer workflow that live in chat.',
      url: 'orbis-dev.netlify.app',
    },
    {
      name: 'TAD COIN',
      blurb: 'A cryptocurrency named after Terry A. Davis.',
      url: 'tad-coin.netlify.app',
    },
    {
      name: 'QB READER',
      blurb: 'A quiz bowl practice site. I work on the web client.',
      url: 'github.com/qbreader/website',
    },
    {
      name: 'ZEP',
      blurb: 'A general-purpose Discord bot.',
      url: 'github.com/wbrous/zep',
    },
    {
      name: 'CORTIS',
      blurb: 'A messaging app built for developers.',
      url: 'NOT RELEASED',
    },
  ],
};

export const COLOPHON = {
  contactEyebrow: 'ELSEWHERE',
  contact: [
    { label: 'EMAIL', value: 'lawrence@reamus.app' },
    { label: 'DISCORD', value: 'btf_cookies' },
    { label: 'EIGHTBIT LABS', value: 'eightbitlabs.netlify.app' },
  ],
  colophonEyebrow: 'COLOPHON',
  notes: [
    'Sheets are generated by scripts/build.mjs from live GitHub data and refreshed daily.',
    'The constraint is no colour. With no hue to spend, volume becomes dot area, category becomes fill pattern, and the avatar is dithered to one bit so its rainbow reads as density.',
    'Archivo Black and IBM Plex, baked to outlines — web fonts do not load inside a README image.',
  ],
};
